### PR TITLE
build: enable esModuleInterop for build

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This enables the `esModuleInterop` flag in the `tsconfig`.  Doing this for a few reasons:
- I don't believe we export d.ts types, which can cause problems downstream
- It's the default for TypeScript's out of the box config
- It's about to be the default for `gts`

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@alexander-fenster I am having a ton of trouble debugging this :( AFAICT using esModuleInterop like this shouldn't break webpack.  Any chance you could take a peek?

**Comment by alexander-fenster** [comment]
Good that we have tests! :)  I will take a look on Monday when I get back from a small vacation.

**Comment by alexander-fenster** [comment]
@JustinBeckwith  Can you assign this to me so that it appears on my radar? I don't have rights to do that :)

**Comment by JustinBeckwith** [comment]
@alexander-fenster I invited you to the repo :)

**Comment by alexander-fenster** [comment]
@JustinBeckwith It went mad trying to use `fetch` from `node-fetch` in webpack bundle. It should not, since `window.fetch` exists, so I fixed it with [this commit](https://github.com/JustinBeckwith/gaxios/pull/70/commits/cf28a030091e48213bed2995ad2326f6acd75fdd). Works now!

**Comment by alexander-fenster** [comment]
upd. `node-fetch` has `browser` key in its `package.json` and it just used its `node_modules/node-fetch/browser.js` so it all should have worked but did not :)

**Pull request merged**
